### ISSUE TITLE
Internal events don't work with non-pickable payload

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/lahja#17]
## What was wrong?

One of the main motivations for the *internal* events is to be able to broadcast events that stay within one `Endpoint` (and hence `Process`) and allow those to use non-pickable events as well.

Unfortunately, the simple implementation doesn't work in practice. Trying to use this in practice leaves me with:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in uvloop.loop.Loop.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

I believe what happens is that even if the event does not intent to move across process boundaries, simply pushing it into a `multiprocessing.Queue` enforces a *pickability* check.

## How can it be fixed?

Probably route these events into a special purpose local queue.

**Comment by cburgdorf** [comment]
This was fixed in #18
